### ISSUE TITLE
Contao Manager

### ISSUE THREAD

**Issue by 9teufel** [marcosimbuerger/contao-isotope-customer-notes#1]
Leider wird das Modul nicht im Manager angezeigt. 

Contao 4.4.47
Isotope 2.6.9

Danke!

**Comment by marcosimbuerger** [comment]
Hi @mecintosch 

Das Modul war ursprünglich auch nicht gedacht, um es im Manager zu veröffentlichen. Da aber das Bedürfnis besteht, werde ich das Modul demnächst überarbeiten und reinstellen.

**Comment by marcosimbuerger** [comment]
Wenn Du es schon mal testen willst, kannst Du das Repo einfach in Deiner composer.json angeben. Danach kannst Du es installieren mit `composer require marcosimbuerger/contao-isotope-customer-notes`

```
"repositories": [
    {
        "type": "git",
        "url": "https://github.com/marcosimbuerger/contao-isotope-customer-notes.git"
    }
],
```

**Comment by con2net** [comment]
Ich habe oft das Problem, dass die Composer-Operationen auf der Konsole bei mir aus Ressourcengründen scheitern und ich den hier beschriebenen Weg nicht gehen kann. Ich habe mir jetzt so beholfen, das Paket hier aus Github herunterzuladen und dann im Contao Manager über "Pakete hochladen" in die Installation einzubringen. 
Dabei wurde zunächst noch eine fehlende Versionsnummer in der composer.json angemeckert. Dies habe ich durch das hinzufügen von `"version": "1.0.0",` im oberen Block "gelöst" und Contao Manager hat mir dann das Paket einwandfrei installiert. 
Die Funktion deiner Erweiterung ist übrigens super. Wäre bestimmt gut im öffentlichen Repository aufgehoben ;-)

**Comment by marcosimbuerger** [comment]
Hi Stefan

Wie viel PHP Memory hast Du denn zu Verfügung (`php -i |grep memory_limit`)? Alternativ könntest Du z.B. auch versuchen composer mit max. Memory auszuführen. `php -d memory_limit=-1 ~/bin/composer` (Pfade zu PHP und Composer musst Du ggf. gemäss Deiner Umgebung anpassen).

Danke! Falls ich mal mehr Zeit finde, packe ich das ins öffentliche Repo 😄  👍

**Comment by con2net** [comment]
Moin Marco,
ja, theoretisch ;-) Ich habe immer wieder, vor allem bei Installationen mit vielen Erweiterungen, Probleme mit dem Menory an der Konsole. Auch "max. Memory ist ja irgendwann zuende ;-). Vor allem bei Kundeninstallationen kann ich -1 auch selten anbringen und dann muss Kreativität her ;-). Mit dem privaten Paket kann man das gut lösen und hier "fehlte" nur die Kleinigkeit mit der Version und das wollte ich nur kurz anmerken. 
Ja, ja, die Zeit - Danke Dir auf jeden Fall für die Erweiterung (und auch deine tollen Tipps auf deiner Webseite)

**Comment by marcosimbuerger** [comment]
Das Modul ist jetzt bei packagist vorhanden und kann normal via composer installiert werden:
https://packagist.org/packages/marcosimbuerger/contao-isotope-customer-notes
