### ISSUE TITLE
Isotope Customer Notes and PHP8.

### ISSUE THREAD

**Issue by hangarsieben** [marcosimbuerger/contao-isotope-customer-notes#2]
Hi there! At some point, will there be a version of this bundle that adds compatibility with PHP8.1? At the moment it's the only incompatible bundle that keeps me from updating the system.

**Comment by fenepedia** [comment]
I have allowed PHP8 in composer.json for the time being. Looks quite good at first glance.
see PR #3

**Comment by marcosimbuerger** [comment]
PR merged.
